name = "InteractiveFunction"
uuid = "915ec3d0-cb8e-432f-a2e7-8e1c0d600181"
authors = ["michikawa07 <michikawa.ryohei@gmail.com> and contributors"]
version = "0.1.2"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
